### ISSUE TITLE
[Effective C++] C++ 스마트 포인터와 Java의 Garbage Collector 차이

### ISSUE THREAD

**Issue by seongahpark** [seongahpark/CPPBookStudy#45]
## Page
> p.118-123

## Question
최근에 C++의 스마트 포인터와 Java나 C#의 Garbage Collector을 따로 공부하다가 의문점이 들었습니다.
둘 다 메모리 누수를 막기 위해 메모리를 자동 해제해주는 것인데 같은 개념이 아닌가?

궁금해서 구글링을 해보니 다음 내용을 발견할 수 있었습니다
> 가비지컬렉터의 경우 메모리를 할당한 변수들을 전부 돌면서 확인하는 꽤 큰 비용의 과정을 거치지만 C++의 스마트포인터는 내가 지정한 변수들에 대해서만 검사를 진행할 수 있다는 큰 강점을 가지고 있다고 생각한다

그리고 GC와 스마트 포인터 중 shared_ptr과 동작 원리가 비슷하다고 생각했는데 다른 분들의 의견도 궁금합니다

- [ ] #46
- [ ] #47

## 참고 사항
[참고 글](https://drag0n.tistory.com/19)

**Comment by seongahpark** [comment]
옆에 실수로 convert issue 버튼 눌렀는데 취소가 안되네요..

**Comment by hhj3258** [comment]
"하지만 가비지 컬렉션에는 단점이 존재한다. 일단 가비지 컬렉터는 실시간으로 사용되지 않는 메모리를 지워주는 것이 아니다. 위에서 설명했듯이 주기적으로 돌면서 확인하고 지우는 것이기 때문에 사용되지 않는 메모리가 지워지지 않고 충분히 남아있을 수 있다. 이 말은 프로그램이 종료될 때까지 사용되지 않는 메모리가 남아있을 수 있다는 말이다. 따라서 가비지 컬렉터는 메모리 누수를 완벽하게 막지 못할 수 있다."
참고 : https://woo-dev.tistory.com/61

가비지 컬렉터가 언어나 환경마다 좀 다르게 구현되어 있는거 같아서 확실히 이럴 것이다! 라고 하긴 좀 힘드네요.
언리얼 같은 경우에는 가비지 컬렉터의 주기를 설정해줄 수 있는 것 같습니다. 즉 일정 주기마다 대청소를 해주는 느낌이네요. 
위에 블로그처럼 루트가 닿지 못하는(마킹하지 못하는) 부분을 주기적으로 한 번에 밀어주니까 버벅이는 현상도 있을 수 있구요.

c++처럼 사용자가 직접 메모리를 관리하게 되면 일정 주기로 마킹되지 않은 것들을 한 번에 정리해주는 가비지 컬렉터보다 오버헤드가 적고 바로바로 메모리 해제를 해주니까 버벅임도 적을 것 같습니다.

ps. 그래도 전 가비지컬렉터가 좋네요...
