### ISSUE TITLE
[Effective C++] 클래스 내의 static 멤버의 선언과 정의의 차이가 뭔가요?

### ISSUE THREAD

**Issue by hhj3258** [seongahpark/CPPBookStudy#6]
## Page
> 55p - 56p
## Question
- [ ] 55p의 예제 코드에 ```static const int NumTurns = 5;``` 는 '선언'이며, '정의'가 아니니 주의하세요. 라는 구문이 있습니다.
하지만 56p의 예제 코드에서는 ```static const double FudgeFactor;``` 를 '선언' 이라고 하고 있습니다.
뭔가 말이 어긋나는 느낌이라 정확히 알수가 없네요.
첫번째 코드는 '정의' 이고 두 번째 코드는 '선언'이 아닌가요?

## 참고 사항
[C++] static const에 대한 고찰 - https://yongho1037.tistory.com/515

**Comment by seongahpark** [comment]
저도 이부분 되게 이상하다고 생각했었는데
제 의견은 클래스 내부에서 정적 멤버로 만들때는 선언만 가능해서 책에서 그렇게 표현한거 같습니다.
static 변수는 class 멤버 변수에서 선언만 가능하지만 static const는 예외적으로 초기화까지 가능하긴 합니다.
근데 static 특성에 초점을 맞춰서 선언이라고 한게 아닐까요?? 정의되기 전에 static에 의해 이미 메모리에 할당이 돼서..?

선언 : 코드에 사용되는 ‘어떤 대상’의 이름과 타입을 컴파일러에게 알려 주는 것
정의 : 언에서 빠진 구체적인 세부사항을 컴파일러에게 제공, 메모리에 할당
초기화 : 어떤 객체에 최초의 값을 부여하는 과정

#### 참고사항
---
https://salkuma.wordpress.com/2014/02/05/%EC%84%A0%EC%96%B8-%EC%A0%95%EC%9D%98-%EC%B4%88%EA%B8%B0%ED%99%94-%EA%B8%B0%EB%B3%B8%EC%83%9D%EC%84%B1%EC%9E%90-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EC%8B%9C%EA%B7%B8%EB%84%88%EC%B2%98/

**Comment by Park52** [comment]
![image](https://user-images.githubusercontent.com/23352772/150750725-d13795c5-225e-4fb7-bfbd-2cc7bc4aece4.png)

```cpp
#include <iostream>

static const int d = 0;

int main(void)
{
	int a = 0;
	static int b = 0;
	static const int c = 0;

	std::cout << "test" << std::endl;

	return 0;
}
```

확인해보니, 사용하지 않으면 컴파일러 최적화 기능때문에 메모리로 잡히지 않는 것 같네요!
자세한 건 모르겠으나, 참고로 올려주신 블로그 보면 영역 자체가 다르다보니 정의라는 개념이 어울리지 않다.
라고 보는게 아닐까 싶습니다.

**Comment by hhj3258** [comment]
static 으로 만들면 '사용'하기 전까지는 '선언'만 할 수 있다고 받아들이면 될 것 같네요.
'사용'하게 되면 메모리에 올라가서 '정의'되는 것 같구요.
